services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: tomie-erp-postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: tomie-erp-backend
  #   ports:
  #     - '3030:3000'
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/src
